title: Testing Blog
author: Gordon Wang
email: 13385032@qq.com
description: > # this means to ignore newlines until "baseurl:"
  The first blog for testing purpose.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
